name: md2pdf-client
version: 1.0.0
summary: Use an md2pdf server to render Markdown text into a pretty PDF
description: |
    md2pdf is a little project that aims to make it easy to produce \
    professional-looking PDF documents from Markdown files via a LaTeX template \
    and the help of Pandoc.

    With with an appropriate template, LaTeX PDF output is undeniably the prettiest-\
    looking way to create documents. But, learning LaTeX is hard. Markdown \
    is much easier to use, and when used with Pandoc can still produce superb PDF \
    documents. md2pdf makes it simple to manage having the right LaTeX templates \
    and configuration across a whole team, by using a central server to do the PDF \
    generation and then share the result with those who need it.

    This simple Python program is the md2pdf client application. It is intended to \
    be used with an `md2pdf-webserver` instance, running locally or remotely.

icon: icon.svg
grade: stable
confinement: strict

parts:
  md2pdf-client:
    plugin: python
    python-version: python3
    source-type: git
    source: https://github.com/seanlano/md2pdf-client.git
    source-tag: v1.0.0
    requirements: requirements.txt

apps:
    md2pdf-client:
        command: md2pdf_client
        plugs: [network, home]
